name: build and publish

on:
  push:
    branches:
       - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: fetch dependencies
        run: npm ci
      - name: build website
        run: npm run build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: _site
          fqdn: mvion.fr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}